
FROM ubuntu:25.04

WORKDIR /app


RUN apt-get update && apt-get install -y python3 python3-pip python3-debugpy make

RUN pip install hatch --break-system-packages

COPY pyproject.toml README.md ./
COPY src/server_manager/__about__.py /app/src/server_manager/__about__.py

COPY . .
RUN hatch env create
RUN hatch run pip install -e .
